### ISSUE TITLE
Refresh Services References Proxies and Extend `Get-IshTypeFieldDefinition` to support DataType ISHMetadataBinding

### ISSUE THREAD

**Issue by OlegTokar** [sdl/ISHRemote#106]
Adapt ISHRemote to support the modified Settings25.RetrieveFieldSetupByIshType holding ISHMetadataBinding information available since 14SP4/14.0.4

*Make sure to look at the shelved code changes of #58* 

- [x] Add extra DataType ISHMetadataBinding in the enum DataType at \Objects\Enumerations.cs
- [x] Initialize DataType in the IshTypeFieldDefinition  creation using the xml element
- [x] Add extra property allowonsmarttagging to the IshTypeFieldDefinition class at \Objects\Public\IshTypeFieldDefinition.cs
- [x] Add property initialization at IshTypeFieldDefinition constructor
- [x] - Adapt CompareTo method that is needed for comparing objects
- [x] Check Compare-IshTypeFieldDefinition is working
- [x] Add/Adapt Pester tests

**Comment by ddemeyer** [comment]
@OlegTokar 
1. Issue #58 explains how to implement ISHMetadataBinding visibility in `Get-IshTypeFieldDefinition` across all supported versions. Starting in 14SP4/14.0.4, the Settings25 API call will be extended, see issue #106 so make sure to align implementation between these two issues.
1. So after implementation of #106, issue #58 serves as backfilling for the _older_ versions so `Get-IshTypeFieldDefinition` works the same on any version by explicitly getting and parsing the extension configuration. 
1. Next the "Field has configured metadata binding and it's value type can only be 'id' or 'element'" bug can be fixed, as the field can now be filtered on a write operation. Also covered under #58

**Comment by ddemeyer** [comment]
![image](https://user-images.githubusercontent.com/19798225/103749917-6afe2b00-5006-11eb-8488-6274e1c34f46.png)
