### ISSUE TITLE
Add `Test-IshSession`

### ISSUE THREAD

**Issue by ddemeyer** [sdl/ISHRemote#12]
Wrap `New-IshSession` and its variation in a simple test resulting in $true or $false.

On the side this is a simple cmdlet that checks if `ISHWS` and `ISHSTS` (or other STS) is up-and-running. Together with a simple `.ASP` call all FrontEnd services  can be tested.

These lines of code activate and hence test the WebServices (ISHWS-activation), SecureTokenServices (ISHSTS-activation) and validates the credentials in the 'InfoShare' database (ConnectionString-activation). The extra .ASP line triggers WebClient (ISHCM-activation) and the COM+ application (Trisoft-InfoShare-Author).

`Test-IshSession -WsBaseUrl "https://example.com/ISHWS/" -IshUserName "admin" -IshPassword "admin" -IgnoreSslPolicyErrors -Verbose
Invoke-WebRequest -Uri "https://example.com/ISHCM/InfoShareAuthor.asp" -UseBasicParsing`

**Comment by Sarafian** [comment]
For future reference this is an example gist on how to use [WcfPS](https://www.powershellgallery.com/packages/WcfPS/1.0) to access the ISHCM endpoints.
