### ISSUE TITLE
Get baseline ID from publication ID

### ISSUE THREAD

**Issue by roopeshnavath** [sdl/ISHRemote#24]
Is there any way to get baselineID(not baseline items) using publication ID and Version with ISHRemote?
This is not an issue, an enhancement request.

**Comment by ddemeyer** [comment]
For completeness cross posting the answer that was given on https://community.sdl.com/solutions/content-management/knowledge-center/knowledgecenter-developers/f/215/p/13887/50803?Redirected=true#50803
[...]
The -RequestedMetadata parameter ensures only that the returned IshObjects have the desired metadata. Here we need to filter all possible IshObjects by version so we'd use the -MetadataFilter parameter with an object created by Set-IshMetadataFilterField.
PS migration> function getPublicationContent ($pubid, $version_number){
  ```
$requestedMetadata = Set-IshMetadataField -IshSession $session -Name FISHBASELINE -Level Version -ValueType Element
  $metadataFilter = Set-IshMetadataFilterField -IshSession $session -Name 'VERSION' -Level Version -Value $version_number
  $pub        = Get-IshPublicationOutput -IshSession $session -LogicalId $pubid -RequestedMetadata $requestedMetadata -MetadataFilter $metadataFilter
  $baselineid = $pub | Get-IshMetadataField -IshSession $session -Name FISHBASELINE -Level Version -ValueType Element
  $baseline   = Get-IshBaseline -IshSession $session -Id $baselineid
  $content    = Get-IshBaselineItem -IshSession $session -IshObject $baseline
  $content
}
```
And then, to continue my previous example, you can get the content of version 2 of a publication in this way:
`PS migration> getPublicationContent $pub.IshRef 2`
[...]
