### ISSUE TITLE
Improving New-IshSession for Windows Authentication

### ISSUE THREAD

**Issue by HildeVermeiren** [sdl/ISHRemote#37]
We are using the New-IshSession cmdlet from within wrapper PowerShell scripts. Since we need to support the script both for ISHSTS and ADFS, we have a helper method that checks if the incoming username is empty or not:
````
if ($ishUserName.Length -eq 0)
{
  # Connection via Windows Authentication
  $ishSession = New-IshSession -WsBaseUrl $wsBaseUrl
}
else
{ 
  # Connection via InfoShareSTS
  $ishSession = New-IshSession -WsBaseUrl $wsBaseUrl -ishUserName $ishUserName -IshPassword $ishPassword
}
````

It would be nice if ISHRemote would not throw an exception when you call New-IshSession with an empty username, but instead automatically switches to Windows Authentication.

**Comment by ddemeyer** [comment]
Had something like that on my private backlog list as 

> ParameterSets now clearly separate Username/Password (ISHSTS) from Credential (ADFS) which means that calling code, that doesn't know the authentication type, needs wrapper code.Request is to fallback - with a warning - that if an empty Username is presented that the code falls back to network credential (ADFS) style. This way PS1 scripts always use Username/Password but if provided empty (over InstallTool) then the ISHRemote code does the fall back to Windows Authentication.
