### ISSUE TITLE
how to cancel the publication using powershell?

### ISSUE THREAD

**Issue by bhupathirajupavanvarma** [sdl/ISHRemote#39]

**Comment by ddemeyer** [comment]
The most basic cancel example is listed below. If the status transition on the PublicationOutput level allows it, it will push the publication status into cancelled. On the next attempt on the publishing job, the BackgroundTask service will check if the current status of the PublicationOutput object is cancelled and then stop the BackgroundTask from continuing.
```
$ishSession = New-IshSession -WsBaseUrl "https://example.com/ISHWS/" -PSCredential "Admin"
$metadataUpdate = Set-IshMetadataField -IshSession $ishSession -Name FISHPUBSTATUS -Level lng -ValueType Element -Value VPUBSTATUSPUBLISHINGCANCELLED
Set-IshPublicationOutput -IshSession $ishSession -LogicalId "GUID-F66C1BB5-076D-455C-B055-DAC5D61AB3D9" -Version "1" -OutputFormat "GUID-2A69335D-F025-4963-A142-5E49988C7C0C" -LanguageCombination "en" -MetaData $metadataUpdate
```
As noted in #40, next ISHRemote version will support pipeline IshObject.
