### ISSUE TITLE
Dropping SSL 3 support; adding TLS 1.0, TLS 1.1 and TLS 1.2 avoiding HTTPS handshake failures

### ISSUE THREAD

**Issue by ddemeyer** [sdl/ISHRemote#5]
`HTTPS handshake to ...com failed. System.IO.IOException Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. < An existing connection was forcibly closed by the remote host`

The load balancer in question was setup using `ELBSecurityPolicy-TLS-1-2-2017-01` (so TLS 1.2) while standard .NET 4.5 will do SSL 3 and TLS 1.0. The mismatch caused the HTTPS handshake to fail. Roll back to ELBSecurityPolicy-TLS-1-0-2015-04 worked. Same for `Invoke-WebRequest` by the way.

Solution is to only support TLS (1.0, 1.1 and 1.2), remove SSL3 as it is flawed anyway. See http://msdn.microsoft.com/en-us/library/system.security.authentication.sslprotocols(v=vs.110).aspx

`private static SecurityProtocolType _securityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
System.Net.ServicePointManager.SecurityProtocol = _securityProtocol;`

**Comment by Sarafian** [comment]
Code sample

```
# Create an enum instance for TLS, TLS11 and TLS12
private static SecurityProtocolType _securityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

# Set the security protocol
System.Net.ServicePointManager.SecurityProtocol = _securityProtocol;
```

I'll create a pull request

**Comment by Sarafian** [comment]
Pull request GH-6 available for review.
