### ISSUE TITLE
Get-IshFolderLocation -FolderId 0 should not return "\General" folder

### ISSUE THREAD

**Issue by otokar** [sdl/ISHRemote#62]
Cmdlet `Get-IshFolderLocation` should not return `\General` folder when zero value is passed into FolderId parameter. Expected behavior "Folder not found" exception or similar

Verify near line 139 of GetIshFolderLocation.cs

```
PS C:\Users\ddemeyer> Get-IshFolderLocation -FolderId 0
\General

PS C:\Users\ddemeyer> Get-IshFolderLocation -FolderId $null
Get-IshFolderLocation : Cannot validate argument on parameter 'FolderId'. The argument is null or empty. Provide an argument that is not null or empty, and 
then try the command again.
At line:1 char:33
+ Get-IshFolderLocation -FolderId $null
+                                 ~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-IshFolderLocation], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Trisoft.ISHRemote.Cmdlets.Folder.GetIshFolderLocation
```

**Comment by ddemeyer** [comment]
In the past `ParameterSetName` was not available as `TrisoftCmdlet` derived from Microsoft's `Cmdlet`. Later I changed this to Microsoft's `PSCmdlet` but didn't bother updating all of those check null if clauses.

Fix looks good, tests still have to be verified though

**Comment by otokar** [comment]
Tests where cmd-let is used were green locally..
Now it is also much easier to see what is the logic in the "prepare" section, compared to the number of if/else
