### ISSUE TITLE
Replace $env:temp with "[System.IO.Path]::GetTempPath()" in all tests

### ISSUE THREAD

**Issue by HildeVermeiren** [sdl/ISHRemote#74]
The test "Trisoft.ISHRemote/Cmdlets/FileProcessor/NewIshObfuscatedFile.Tests.ps1" uses a TEMP folder for saving the file. When the TEMP folder is selected via "$env:temp", the test fails with:
 ```
    Context New-IshObfuscatedFile
    [+] GetType().Name 732ms
    [-] OutputFilePath 73ms
      Expected: {True}
      But was:  {False}
      64:                  ($taskFileInfo.FullName -eq (Join-Path -Path $outputFolder -ChildPath "task==1=en.xml")) | Should Be $True
      at <ScriptBlock>, C:\Stash\ISHRemote\Source\ISHRemote\Trisoft.ISHRemote\Cmdlets\FileProcessor\NewIshObfuscatedFile.Tests.ps1: line 64  
```

This is only an issue when one of the folders in the path is longer than 8 characters.
$env:Temp returns "C:\Users\HVERME~1\AppData\Local\Temp" for the path "C:\Users\hvermeiren\AppData\Local\Temp"

In order to avoid issues in the future and have a consistent behavior everywhere, we should replace all usages of "$env:temp" by "[System.IO.Path]::GetTempPath()" in the tests.

**Comment by ddemeyer** [comment]
Fixed in v0.11
