### ISSUE TITLE
Add cmdlets *-IShAnnotation

### ISSUE THREAD

**Issue by OlegTokar** [sdl/ISHRemote#78]
We need cmdlets, that would allow Create, Read, Update, Delete, Find operations on Annotations and Replies

Must haves are
- [x] Attempt optional IshSession
- [x] Basic skeleton
- [x] Xml parsing
- [ ] Console formatting --> Separated to #89
- [ ] Attempt RequestedMetadata with overload of Basic, Descriptive, All  --> Separated to #89
- [x]  `Add-IshAnnotation`
- [x]  `Get-IshAnnotation`
- [x]  `Set-IshAnnotation`
- [x]  `Remove-IshAnnotation`
- [x]  `Find-IshAnnotation`

Could haves are
- `Add-IshAnnotationReply`, can be handled over `Add-IshAnnotation` with extra `-Metadata`
- `Find-IshAnnotation`, can be handled over `Find-IshAnnotation` with extra `-MetadataFilter`
- `Remove-IshAnnotationReply`, note that Remove-IshAnnotation already holds a `-Force` flag to delete replies, the use case of explicitly deleting a single reply is small
- `Set-IshAnnotationReply`, this one can be implemented over `Set-IshAnnotation` with extra `-Metadata`

## Add-IshAnnotation

[ParametersGroup]
(o)	>**IshSession** IshSession
(m)	>**string** PubLogicalId
(m)	>**string** PubVersion
(m) >**string** PubLng (version 14.0.2 and higher)
(m)	>**string** LogicalId (get latest RevisionId for LogicalId/Version/Language combination)
(m)	>**string** Version
(m) >**string** Lng
(m)	>**string** Type (enum?)
(m)	>**string** Text
(m)	>**string** Status (enum?, type=value)
(m)	>**string** Address (...users will have troubles to correctly fill this in )
(m)	>**string** Category (enum?)
(o)	>**IshField[]** Metadata (so extra fields e.g. FISHANNOTPROPOSEDCHNGTXT; CmdLet parameters take precedence over value in Metadata)
	<**IshAnnotation** IshAnnotation 
	
[MetadataGroup]
(o)	>**IshSession** IshSession
(m)	>**IshField[]** Metadata (you can pass any metadata that API would allow, e.g. to create orphaned annotations etc)
	<**IshAnnotation** IshAnnotation 
	
[IshObjectGroup] 
(o)	>**IshSession** IshSession
(m) >**IshObject** IshObject (of type ISHModule, for the latest RevisionId create annotation )
(m)	>**string** PubLogicalId
(m)	>**string** PubVersion
(m)	>**string** Type (enum)
(m)	>**string** Text
(m)	>**string** Status (enum, type=value)
(m)	>**string** Address (users will have troubles to correctly fill this in )
(m)	>**string** Category (enum)
(o)	>**IshField[]** Metadata (so extra fields e.g. FISHANNOTPROPOSEDCHNGTXT; CmdLet parameters take precedence over value in Metadata)
	<**IshAnnotation** IshAnnotation 

[IshAnnotationGroup]
(o)	>**IshSession** IshSession
(m) >**IshAnnotation[]** IshAnnotation
	<**IshAnnotation** IshAnnotation 

## Set-IshAnnotation

[ParametersGroup]
(o)	>**IshSession** IshSession
(m) >**string** AnnotationId
(o) >**IshField[]** Metadata
(o) >**IshField[]** RequiredCurrentMetadata
	<**IshAnnotation** IshAnnotation 

[IshAnnotationGroup]	
(o)	>**IshSession** IshSession	
(m) >**IshAnnotation[]** IshAnnotation
(o) >**IshField[]** Metadata
(o) >**IshField[]** RequiredCurrentMetadata	
	<**IshAnnotation** IshAnnotation 

## Remove-IshAnnotation
- by default deletes replies prior to deletion of an annotation
[ParametersGroup]
(o)	>**IshSession** IshSession
(m) >**string** AnnotationId

[IshAnnotationGroup]	
(o)	>**IshSession** IshSession	
(m) >**IshAnnotation[]** IshAnnotation

	

## Get-IshAnnotation

[ParametersGroup]
(o)	>**IshSession** IshSession
(m) >**string[]** AnnotationIds
(o) >**IshField[]** MetadataFilter
(o) >**IshField[]** RequestedMetadata	
	<**IshAnnotation[]** IshAnnotation 

[IshAnnotationGroup]	
(o)	>**IshSession** IshSession	
(m) >**IshAnnotation[]** IshAnnotation
(o) >**IshField[]** RequestedMetadata	
	<**IshAnnotation[]** IshAnnotation 

[IshObjectGroup]
(o)	>**IshSession** IshSession	
(m) >**IshObject[]** IshObject ("ISHModule"=getting annotation for all versions and revisions(?), "ISHPublication"=getting annotations for the given FISHPUBLOGICALID & FISHPUBVERSION.)
(o) >**IshField[]** RequestedMetadata	
	<**IshAnnotation[]** IshAnnotation 

_Note:_

1.  We are using Find call in Get-cmdlet
1.  For ISHPublication object we are finding only using FISHPUBLOGICALID & FISHPUBVERSION combination, so we don't care about baseline items

	
## Find-IshAnnotation
	
[ParametersGroup]
(o)	>**IshSession** IshSession
(o) >**IshField[]** MetadataFilter
(o) >**IshField[]** RequestedMetadata	
	<**IshAnnotation[]** IshAnnotation 

## Add-IshAnnotationReply

[ParametersGroup]
(o)	>**IshSession** IshSession
(m)	>**string** AnnotationId
(m) >**string** Text
	<IshAnnotationReply IshAnnotationReply 

[ISHAnnotationGroup]
(o)	>**IshSession** IshSession
(m)	>**IshAnnotation[]** IshAnnotation
(m) >**string** Text
	<**IshAnnotationReply[]** IshAnnotationReply 

[MetadataGroup]
(o)	>**IshSession** IshSession
(m)	>**string** AnnotationId
(m) >**IshField[]** Metadata
	<**IshAnnotationReply** IshAnnotationReply 
	
[ISHAnnotationReply group ?]

## Set-IshAnnotationReply

[ParametersGroup]
(o)	>**IshSession** IshSession
(m)	>**int** ReplyId
(o) >**IshField[]** Metadata
(o) >**IshField[]** RequiredCurrentMetadata
	<**IshAnnotationReply** IshAnnotationReply 

[IshAnnotationReplyGroup]
(o)  >**IshSession** IshSession
(m) >**ISHAnnotationReply[]** ISHAnnotationReply
(o) >**IshField[]** Metadata
(o) >**IshField[]** RequiredCurrentMetadata
	<**IshAnnotationReply[]** IshAnnotationReply 

## Remove-IshAnnotationReply

[ParametersGroup]
(o)	>**IshSession** IshSession
(m)	>**int** ReplyId

[IshAnnotationReplyGroup]
(o)	>**IshSession** IshSession
(m) >**ISHAnnotationReply[]** ISHAnnotationReply

**Comment by ddemeyer** [comment]
Remaining tweaks were separated to #89, allowing to close this issue on v0.11
